### PR TITLE
Winter Semester 23 vvvv intermediate workshops

### PR DESCRIPTION
**Pull request by baxtan**

### CODE REVIEW

**Comment by joreg** [comment]
- please add include "/24" at the end of the title to show this reaches over to 2024
- please add kathls url even though it seems broken at this point (let's assume it comes up again)
- all workshop are running from 6-9pm CET on thursdays, so mention that once at the beginnging
- then for the listing: date first: title (remove any mention of vvvv in the titles since context is clear), then host
- add "(Free!)" after the title for the two free ones (transformations, fuse intro)

**Comment by baxtan** [comment]
@joreg Should I leave "Châtaigne and vvvv: Powering Multimedia Installations" as is, or you prefer:
"Châtaigne: Powering Multimedia Installations" ?

**Comment by joreg** [comment]
right in this case, leave the "vvvv"

**Comment by joreg** [comment]
grafik

**Comment by joreg** [comment]
to calm the page, for dates please try:
day. month year: 
eg. 24.12 2023:
and not have them bold. hoping like this they'll be easier to grasp.

**Pull request merged**
